{% set build_number = 3 %}
{% set version = "3.0.0-alpha7" %}
{% set version_python = "3.0.0a7" %}
{% set sha256 = "442b06b824441293e72ff91b211a555c5d497aedf62be1c4332c426558b848a4" %}

# win: no PETSc, only python

package:
  name: damask-pkgs
  version: {{ version_python }}

source:
  url: https://damask.mpie.de/download/damask-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - long-lines.patch
    - setup-cfg.patch
    - HDF5-Fortran.patch
    - MPICH.patch
    - T-init.patch
    - PETSc19-1.patch
    - PETSc19-2.patch
    - DMDA.patch
    - DMView.patch

build:
  number: {{ build_number }}

outputs:
  - name: damask-grid
    script: build_grid.sh
    build:
      skip: true  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - libgomp  # [linux]
        - llvm-openmp  # [osx]
        - pkg-config  # [osx]
        - cmake
        - make
        - openmpi  # [mpi == 'openmpi' and build_platform != target_platform]
      host:
        - {{ mpi }}
        - petsc * real_*
        - hdf5 * mpi_{{ mpi }}_*
        - libfyaml
        - fftw * mpi_{{ mpi }}_*
      run:
        - hypre
        - {{ pin_compatible('petsc', max_pin='x.x') }}
        - {{ pin_compatible('hdf5', max_pin='x.x') }}
      run_constrained:
        - damask =={{ version_python }}
    test:
      commands:
        - export OMPI_MCA_plm=isolated
        - export OMPI_MCA_btl_vader_single_copy_mechanism=none
        - export OMP_NUM_THREADS=2
        - if [ $CONDA_BUILD_CROSS_COMPILATION != '1' ]; then mpirun -np 2 DAMASK_grid --help; fi

  - name: damask-mesh
    script: build_mesh.sh
    build:
      skip: true  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - libgomp  # [linux]
        - llvm-openmp  # [osx]
        - pkg-config  # [osx]
        - cmake
        - make
        - openmpi  # [mpi == 'openmpi' and build_platform != target_platform]
      host:
        - {{ mpi }}
        - petsc * real_*
        - hdf5 * mpi_{{ mpi }}_*
        - libfyaml
      run:
        - hypre
        - {{ pin_compatible('petsc', max_pin='x.x') }}
        - {{ pin_compatible('hdf5', max_pin='x.x') }}
      run_constrained:
        - damask =={{ version_python }}
    test:
      commands:
        - export OMPI_MCA_plm=isolated
        - export OMPI_MCA_btl_vader_single_copy_mechanism=none
        - export OMP_NUM_THREADS=2
        - if [ $CONDA_BUILD_CROSS_COMPILATION != '1' ]; then mpirun -np 2 DAMASK_mesh --help; fi

  - name: python-damask
    build:
      script: python -m pip install ./python --no-deps -vv
      skip: true  # [py<38]
    requirements:
      build:
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libxxf86vm') }}  # [linux]
        - {{ cdt('libxext') }}     # [linux]
      host:
        - xorg-libxfixes  # [linux]
        - python
        - pip
      run:
        - python
        - pandas
        - scipy
        - h5py >=3.3.0
        - vtk
        - matplotlib-base
        - pyyaml
      run_constrained:
        - damask =={{ version_python }}
    test:
      imports:
        - damask

  - name: damask
    build:
      script:
        - "echo DAMASK metapackage"
      skip: true  # [py<38 or win]
    requirements:
      host:
        - python
      run:
        - python
        - {{ mpi }}
        - {{ pin_subpackage('damask-mesh', exact=True) }}
        - {{ pin_subpackage('damask-grid', exact=True) }}
        - {{ pin_subpackage('python-damask', exact=True) }}
    test:
      commands:
        - export OMPI_MCA_plm=isolated
        - export OMPI_MCA_btl_vader_single_copy_mechanism=none
        - export OMPI_MCA_rmaps_base_oversubscribe=yes
        - if [ $CONDA_BUILD_CROSS_COMPILATION != '1' ]; then DAMASK_grid -h; DAMASK_mesh -h; fi
      imports:
        - damask

about:
  home: https://damask.mpie.de/
  license: AGPL-3.0-or-later
  license_file:
    - LICENSE
    - COPYING
  summary: 'Duesseldorf Advanced Material Simulation Kit'

  description: |
    At the core of DAMASK is a flexible and hierarchically structured
    model of material point behavior for the solution of elastoplastic
    boundary value problems along with damage and thermal physics. Its
    main purpose is the simulation of crystal plasticity within a
    finite-strain continuum mechanical framework.
  doc_url: https://damask.mpie.de/documentation
  dev_url: https://damask.mpie.de/development

extra:
  recipe-maintainers:
    - jan-janssen
    - MarDiehl
    - yangbai90
