{% set build_number = 2 %}
{% set version = "3.0.0-alpha5" %}
{% set version_python = "3.0.0a5" %}
{% set sha256 = "2d2b10901959c26a5bb5c52327cdafc7943bc1b36b77b515b0371221703249ae" %}

# win: no PETSc, only python

package:
  name: damask-pkgs
  version: {{ version_python }}

source:
  url: https://damask.mpie.de/download/damask-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - PETSc-HDF5-Fortran.patch

build:
  number: {{ build_number }}

outputs:
  - name: damask-grid
    build:
      script:
        - PETSC_DIR=${PREFIX} cmake -B build-grid -DDAMASK_SOLVER=grid -DCMAKE_INSTALL_PREFIX=${PREFIX}
        - cmake --build build-grid --target install
      run_exports:
        - {{ mpi }}
        - petsc
        - hdf5
      skip: true  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - libgomp  # [linux]
        - llvm-openmp  # [osx]
        - pkg-config  # [osx]
        - cmake
        - make
      host:
        - {{ mpi }}
        - petsc * real_*
        - hdf5 * mpi_{{ mpi }}_*
      run:
        - hypre
        - {{ pin_compatible('petsc', max_pin='x.x') }}
        - {{ pin_compatible('hdf5', max_pin='x.x') }}
      run_constrained:
        - damask =={{ version_python }}
    test:
      commands:
        - export OMPI_MCA_plm=isolated
        - export OMPI_MCA_btl_vader_single_copy_mechanism=none
        - export OMP_NUM_THREADS=2
        - DAMASK_grid --help

  - name: damask-mesh
    build:
      script:
        - PETSC_DIR=${PREFIX} cmake -B build-mesh -DDAMASK_SOLVER=mesh -DCMAKE_INSTALL_PREFIX=${PREFIX}
        - cmake --build build-mesh --target install
      run_exports:
        - {{ mpi }}
        - petsc
        - hdf5
      skip: true  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - libgomp  # [linux]
        - llvm-openmp  # [osx]
        - pkg-config  # [osx]
        - cmake
        - make
      host:
        - {{ mpi }}
        - petsc * real_*
        - hdf5 * mpi_{{ mpi }}_*
      run:
        - hypre
        - {{ pin_compatible('petsc', max_pin='x.x') }}
        - {{ pin_compatible('hdf5', max_pin='x.x') }}
      run_constrained:
        - damask =={{ version_python }}
    test:
      commands:
        - export OMPI_MCA_plm=isolated
        - export OMPI_MCA_btl_vader_single_copy_mechanism=none
        - export OMP_NUM_THREADS=2
        - DAMASK_mesh --help

  - name: python-damask
    build:
      script: python -m pip install ./python --no-deps -vv --use-feature=in-tree-build
      skip: true  # [py<37]
    requirements:
      build:
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libxxf86vm') }}  # [linux]
        - {{ cdt('libxext') }}     # [linux]
      host:
        - xorg-libxfixes  # [linux]
        - python
        - pip
      run:
        - python
        - pandas
        - scipy
        - h5py >=3.3.0
        - vtk
        - matplotlib-base
        - pyyaml
      run_constrained:
        - damask =={{ version_python }}
    test:
      imports:
        - damask

  - name: damask
    build:
      script: 
        - "echo DAMASK metapackage"
      skip: true  # [py<37 or win]
    requirements:
      host:
        - python
      run:
        - python
        - {{ mpi }}
        - {{ pin_subpackage('damask-mesh', exact=True) }}
        - {{ pin_subpackage('damask-grid', exact=True) }}
        - {{ pin_subpackage('python-damask', exact=True) }}
    test:
      commands:
        - export OMPI_MCA_plm=isolated
        - export OMPI_MCA_btl_vader_single_copy_mechanism=none
        - export OMPI_MCA_rmaps_base_oversubscribe=yes
        - mpiexec -np 2 DAMASK_grid -h
        - mpiexec -np 2 DAMASK_mesh -h
      imports:
        - damask

about:
  home: https://damask.mpie.de/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'Duesseldorf Advanced Material Simulation Kit'

  description: |
    At the core of DAMASK is a flexible and hierarchically structured
    model of material point behavior for the solution of elastoplastic
    boundary value problems along with damage and thermal physics. Its
    main purpose is the simulation of crystal plasticity within a
    finite-strain continuum mechanical framework.
  doc_url: https://damask.mpie.de/documentation
  dev_url: https://damask.mpie.de/development

extra:
  recipe-maintainers:
    - jan-janssen
    - MarDiehl
