{% set name = "damask" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eisenforschung/DAMASK/archive/v{{ version }}-alpha.tar.gz
  sha256: 2336a51ea88921f8ddad49b4f569b1d8281fc9575dbe6e682a9b18e21b1db4f1

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux] 
    - make
    - cmake
    - numpy
    - perl
  host:
    - python
    - pip
    - xorg-libxfixes  # [linux]
    - petsc =3.10
    - vtk
    # need to list hdf5 and fftw twice to get version pinning from conda_build_config
    # and build pinning from mpi_mpich
    - hdf5
    - fftw
    - hdf5 =*=mpi_mpich_*
    - fftw =*=mpi_mpich_*
    - scipy
    - mpich
  run:
    - python
    - petsc =3.10
    - numpy
    - vtk
    # need to list hdf5 and fftw twice to get version pinning from conda_build_config
    # and build pinning from mpi_mpich
    - hdf5
    - fftw
    - hdf5 =*=mpi_mpich_*
    - fftw =*=mpi_mpich_*
    - scipy
    - mumps-mpi
    - scotch
    - metis
    - scalapack
    - suitesparse
    - parmetis
    - mpich
    - libopenblas
    - hypre
    - ptscotch
    - _openmp_mutex

test:
  commands:
    - DAMASK_spectral --help
  imports:
    - damask

about:
  home: https://damask.mpie.de/
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Duesseldorf Advanced Material Simulation Kit'

  description: |
    At the core of DAMASK is a flexible and hierarchically structured
    model of material point behavior for the solution of elastoplastic
    boundary value problems along with damage and thermal physics. Its 
    main purpose is the simulation of crystal plasticity within a 
    finite-strain continuum mechanical framework.
  doc_url: https://damask.mpie.de/Documentation/WebHome
  dev_url: https://damask.mpie.de/Development/WebHome

extra:
  recipe-maintainers:
    - jan-janssen
