{% set name = "damask" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eisenforschung/DAMASK/archive/v{{ version }}-alpha3.tar.gz
  sha256: 86cbb66b3bd3ead9b5efb84920d56e7396c260b7e32c885656220f59c8b73550
  patches:
    - python.patch

build:
  number: 10
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - make
    - cmake
    - perl
  host:
    - python
    - numpy
    - pip
    - xorg-libxfixes  # [linux]
    - petsc
    - vtk
    - pillow
    # need to list hdf5 and fftw twice to get version pinning from conda_build_config
    # and build pinning from mpi_mpich
    - hdf5
    - fftw
    - hdf5 =*=mpi_mpich_*
    - fftw =*=mpi_mpich_*
    - scipy
    - mpich
  run:
    - python
    - numpy
    - vtk
    - pandas
    - matplotlib-base
    - scipy
    - h5py
    # need to list hdf5 and fftw twice to get version pinning from conda_build_config
    # and build pinning from mpi_mpich
    - hdf5
    - fftw
    - hdf5 =*=mpi_mpich_*
    - fftw =*=mpi_mpich_*
    - mumps-mpi
    - scotch
    - petsc
    - metis
    - scalapack
    - suitesparse
    - parmetis
    - mpich
    - libopenblas
    - hypre
    - ptscotch
    - _openmp_mutex
    - pyaml

test:
  commands:
    - DAMASK_grid --help
    - pip check
  imports:
    - damask
  requires: 
    - pip

about:
  home: https://damask.mpie.de/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'Duesseldorf Advanced Material Simulation Kit'

  description: |
    At the core of DAMASK is a flexible and hierarchically structured
    model of material point behavior for the solution of elastoplastic
    boundary value problems along with damage and thermal physics. Its 
    main purpose is the simulation of crystal plasticity within a 
    finite-strain continuum mechanical framework.
  doc_url: https://damask.mpie.de/Documentation/WebHome
  dev_url: https://damask.mpie.de/Development/WebHome

extra:
  recipe-maintainers:
    - jan-janssen
    - navyRUB
