{% set name = "damask" %}
{% set version = "3.0.0a4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eisenforschung/DAMASK/archive/v3.0.0-alpha4.tar.gz
  sha256: 92b923b0296aad1f0903b5cd74fb8c3cdbc45725e7400220b10c8065632c85c5
  patches:
    - python.patch
    - cmake.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - libgomp  # [linux]
    - make
    - cmake
    - pkgconfig
    - pip
  host:
    - python
    - numpy
    - pip
    - pandas
    - matplotlib-base
    - h5py
    - xorg-libxfixes  # [linux]
    - libblas
    - petsc
    - vtk
    - pillow
    # need to list hdf5 and fftw twice to get version pinning from conda_build_config
    # and build pinning from mpi_openmpi
    - hdf5
    - fftw
    - hdf5 * mpi_{{ mpi }}_*
    - fftw * mpi_{{ mpi }}_*
    - scipy
    - {{ mpi }}
  run:
    - python
    - numpy
    - vtk
    - pandas
    - matplotlib-base
    - scipy
    - h5py
    # need to list hdf5 and fftw twice to get version pinning from conda_build_config
    # and build pinning from mpi_openmpi
    - hdf5
    - fftw
    - hdf5 * mpi_{{ mpi }}_*
    - fftw * mpi_{{ mpi }}_*
    - mumps-mpi
    - scotch
    - petsc
    - metis
    - scalapack
    - suitesparse
    - parmetis
    - {{ mpi }}
    - hypre
    - ptscotch
    - pyaml

test:
  commands:
    - export OMPI_MCA_plm=isolated
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - export OMPI_MCA_rmaps_base_oversubscribe=yes
    - DAMASK_grid --help
    - pip check
  imports:
    - damask
  requires: 
    - pip

about:
  home: https://damask.mpie.de/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'Duesseldorf Advanced Material Simulation Kit'

  description: |
    At the core of DAMASK is a flexible and hierarchically structured
    model of material point behavior for the solution of elastoplastic
    boundary value problems along with damage and thermal physics. Its 
    main purpose is the simulation of crystal plasticity within a 
    finite-strain continuum mechanical framework.
  doc_url: https://damask.mpie.de/Documentation/WebHome
  dev_url: https://damask.mpie.de/Development/WebHome

extra:
  recipe-maintainers:
    - jan-janssen
    - navyRUB
    - MarDiehl
