{% set version = "3.0.0a4" %}

package:
  name: damask
  version: {{ version }}

source:
  url: https://damask3.mpie.de/download/damask-3.0.0-alpha4.tar.xz
  sha256: 0bb8bde43b27d852b1fb6e359a7157354544557ad83d87987b03f5d629ce5493
  patches:
    - pyaml.patch

build:
  number: 1
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - libgomp  # [linux]
    - make
    - cmake
  host:
    # --------------------------------------------------------------------------------------------
    # python
    - python
    - pandas
    - scipy
    - h5py
    - vtk
    - matplotlib-base
    - pyyaml
    # --------------------------------------------------------------------------------------------
    # Fortran
    - {{ mpi }}
    - petsc
    - libblas
    # need to list hdf5 and fftw twice to get version pinning from conda_build_config
    # and build pinning from mpi_openmpi
    - hdf5
    - fftw
    - hdf5 * mpi_{{ mpi }}_*
    - fftw * mpi_{{ mpi }}_*
  run:
    # --------------------------------------------------------------------------------------------
    # python
    - python
    - pandas
    - scipy
    - h5py
    - vtk
    - matplotlib-base
    - pyyaml
    # --------------------------------------------------------------------------------------------
    # Fortran
    - {{ mpi }}
    - petsc
    - libblas
    - mumps-mpi
    - scotch
    - metis
    - scalapack
    - suitesparse
    - parmetis
    - hypre
    - ptscotch
    # need to list hdf5 and fftw twice to get version pinning from conda_build_config
    # and build pinning from mpi_openmpi
    - hdf5
    - fftw
    - hdf5 * mpi_{{ mpi }}_*
    - fftw * mpi_{{ mpi }}_*
test:
  commands:
    - export OMPI_MCA_plm=isolated
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - export OMPI_MCA_rmaps_base_oversubscribe=yes
    - DAMASK_grid --help
    - DAMASK_mesh --help
    - pip check
  imports:
    - damask
  requires: 
    - pip

about:
  home: https://damask3.mpie.de/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'Duesseldorf Advanced Material Simulation Kit'

  description: |
    At the core of DAMASK is a flexible and hierarchically structured
    model of material point behavior for the solution of elastoplastic
    boundary value problems along with damage and thermal physics. Its 
    main purpose is the simulation of crystal plasticity within a 
    finite-strain continuum mechanical framework.
  doc_url: https://damask3.mpie.de/documentation
  dev_url: https://damask3.mpie.de/development

extra:
  recipe-maintainers:
    - jan-janssen
    - navyRUB
    - MarDiehl
