{% set version = "3.0.0a4" %}

package:
  name: damask-pkgs
  version: {{ version }}

source:
  url: https://damask3.mpie.de/download/damask-3.0.0-alpha4.tar.xz
  sha256: 0bb8bde43b27d852b1fb6e359a7157354544557ad83d87987b03f5d629ce5493
  patches:
    - pyaml.patch

build:
  number: 14

outputs:
  - name: damask-grid
    build:
      script:
        - PETSC_DIR=${PREFIX} cmake -B build-grid -DDAMASK_SOLVER=grid -DCMAKE_INSTALL_PREFIX=${PREFIX}
        - cmake --build build-grid --target install
      run_exports:
        - {{ mpi }}
        - petsc
        - hdf5
      skip: true  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libxxf86vm') }}  # [linux]
        - {{ cdt('libxext') }}     # [linux]
        - libgomp  # [linux]
        - pkg-config  # [osx]
        - cmake
      host:
        - {{ mpi }}
        - petsc * real_*
        - hdf5 >=1.12
        - hdf5 * mpi_{{ mpi }}_*
        - xorg-libxfixes  # [linux]
      run:
        - {{ pin_compatible('petsc', max_pin='x.x') }}
        - {{ pin_compatible('hdf5', max_pin='x.x') }}
      run_constrained:
        - damask =={{ version }}
    test:
      commands:
        - export OMPI_MCA_plm=isolated
        - export OMPI_MCA_btl_vader_single_copy_mechanism=none
        - DAMASK_grid --help

  - name: damask-mesh
    build:
      script:
        - PETSC_DIR=${PREFIX} cmake -B build-mesh -DDAMASK_SOLVER=mesh -DCMAKE_INSTALL_PREFIX=${PREFIX}
        - cmake --build build-mesh --target install
      run_exports:
        - {{ mpi }}
        - petsc
        - hdf5
      skip: true  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libxxf86vm') }}  # [linux]
        - {{ cdt('libxext') }}     # [linux]
        - libgomp  # [linux]
        - pkg-config  # [osx]
        - cmake
      host:
        - {{ mpi }}
        - petsc * real_*
        - hdf5 >=1.12
        - hdf5 * mpi_{{ mpi }}_*
        - xorg-libxfixes  # [linux]
      run:
        - {{ pin_compatible('petsc', max_pin='x.x') }}
        - {{ pin_compatible('hdf5', max_pin='x.x') }}
      run_constrained:
        - damask =={{ version }}
    test:
      commands:
        - export OMPI_MCA_plm=isolated
        - export OMPI_MCA_btl_vader_single_copy_mechanism=none
        - DAMASK_mesh --help

  - name: python-damask
    build:
      script: python -m pip install ./python --no-deps -vv --use-feature=in-tree-build
      skip: true  # [py<37]
    requirements:
      build:
        - {{ cdt('mesa-libgl-devel') }}  # [linux]
        - {{ cdt('mesa-dri-drivers') }}  # [linux]
        - {{ cdt('libselinux') }}  # [linux]
        - {{ cdt('libxdamage') }}  # [linux]
        - {{ cdt('libxxf86vm') }}  # [linux]
        - {{ cdt('libxext') }}     # [linux]
      host:
        - xorg-libxfixes  # [linux]
        - python
        - pip
      run:
        - python
        - pandas
        - scipy
        - h5py >=3.3.0
        - h5py * mpi_{{ mpi }}_*  # [not win]
        - hdf5 >=1.12  # [not win] 
        - hdf5 * mpi_{{ mpi }}_*  # [not win]
        - xorg-libxfixes  # [linux]
        - vtk
        - matplotlib-base
        - pyyaml
      run_constrained:
        - damask =={{ version }}
    test:
      imports:
        - damask

#  - name: damask
#    build:
#      run_exports:
#        - {{ mpi }}
#        - petsc
#        - hdf5
#      script: "echo DAMASK"
#      skip: true  # [win or py<37]
#    requirements:
#      build:
#        - {{ compiler('c') }}
#        - {{ compiler('cxx') }}
#        - {{ compiler('fortran') }}
#        - {{ cdt('mesa-libgl-devel') }}  # [linux]
#        - {{ cdt('mesa-dri-drivers') }}  # [linux]
#        - {{ cdt('libselinux') }}  # [linux]
#        - {{ cdt('libxdamage') }}  # [linux]
#        - {{ cdt('libxxf86vm') }}  # [linux]
#        - {{ cdt('libxext') }}     # [linux]
#        - libgomp  # [linux]
#      host:
#        - xorg-libxfixes  # [linux]
#        - python
#        - {{ mpi }}
#        - petsc * real_*
#        - hdf5 >=1.12
#        - hdf5 * mpi_{{ mpi }}_*
#      run:
#        - pandas
#        - scipy
#        - h5py >=3.3.0
#        - vtk
#        - matplotlib-base
#        - pyyaml
#        - petsc
#        - {{ pin_compatible('petsc', max_pin='x.x') }}
#        - {{ pin_compatible('hdf5', max_pin='x.x') }}
#        - {{ pin_subpackage('damask-mesh', exact=True) }}
#        - {{ pin_subpackage('damask-grid', exact=True) }}
#        - {{ pin_subpackage('python-damask', exact=True) }}
#    test:
#      commands:
#        - export OMPI_MCA_plm=isolated
#        - export OMPI_MCA_btl_vader_single_copy_mechanism=none
#        - export OMPI_MCA_rmaps_base_oversubscribe=yes
#        - mpiexec -np 2 DAMASK_grid --help
#        - mpiexec -np 2 DAMASK_mesh --help
#      imports:
#        - damask

about:
  home: https://damask3.mpie.de/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'Duesseldorf Advanced Material Simulation Kit'

  description: |
    At the core of DAMASK is a flexible and hierarchically structured
    model of material point behavior for the solution of elastoplastic
    boundary value problems along with damage and thermal physics. Its
    main purpose is the simulation of crystal plasticity within a
    finite-strain continuum mechanical framework.
  doc_url: https://damask3.mpie.de/documentation
  dev_url: https://damask3.mpie.de/development

extra:
  recipe-maintainers:
    - jan-janssen
    - navyRUB
    - MarDiehl
